### ISSUE TITLE
about MNIST/GLUON reproduce the result

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [pluskid/fitting-random-labels#2]
hi, Chiyuan, 
what do u mean by

>>>if you are trying to reproduce the results on MNIST, you might need to try harder. MNIST contains digits that are very similar even in the pixel space. So assigning different (random) labels to those visually similar digits makes it quite hard to fit. So you might need to run more epochs or tune the learning rate a bit depending on the specific architecture you use.
>>>

Could u plz explain it a lit more?
Thx!

I am currently fitting the random labels in cifar-10 with gluon.
seems to be really hard

**Comment by pluskid** [comment]
@zhangchen-qinyinghua with cifar-10 it should not be very hard. Make sure you are using a model with relatively large capacity and you might want to turn of data augmentation to see if it works. 

MNIST is 'harder' means that the digit images are very similar. If your target function assign very different labels to images that are very similar, then you have a very complicated function to learn (in other words, it changes a lot in a small local neighborhood). Hope this clarifies your question.

**Comment by zhangchen-qinyinghua** [comment]
@pluskid 
Sorry for the stupid question. I look of MNIST as MXNET....
